"""empty message

Revision ID: 6518b2ae9b45
Revises: 
Create Date: 2018-04-08 17:40:59.074076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6518b2ae9b45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'D_O_B',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id', 'user', ['user_id'], unique=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'lastname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'D_O_B',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_table('instruction',
    sa.Column('instruction_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('step_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('direction', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], [u'recipe.recipe_id'], name=u'instruction_ibfk_1'),
    sa.PrimaryKeyConstraint('instruction_id', 'recipe_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('needs',
    sa.Column('ingredient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.FLOAT(), nullable=False),
    sa.Column('measurement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], [u'ingredients.ingredient_id'], name=u'needs_ibfk_1'),
    sa.ForeignKeyConstraint(['measurement_id'], [u'measurement.measurement_id'], name=u'needs_ibfk_3'),
    sa.ForeignKeyConstraint(['recipe_id'], [u'recipe.recipe_id'], name=u'needs_ibfk_2'),
    sa.PrimaryKeyConstraint('ingredient_id', 'recipe_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('meal_plan',
    sa.Column('mealplan_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('mealplan_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('measurement',
    sa.Column('measurement_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('measurement_name', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('measurement_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('plan_generate',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('mealplan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mealplan_id'], [u'meal_plan.mealplan_id'], name=u'plan_generate_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=u'plan_generate_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'mealplan_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('contains',
    sa.Column('mealplan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('meal_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], [u'meal.meal_id'], name=u'contains_ibfk_2'),
    sa.ForeignKeyConstraint(['mealplan_id'], [u'meal_plan.mealplan_id'], name=u'contains_ibfk_1'),
    sa.PrimaryKeyConstraint('meal_id', 'mealplan_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('profile',
    sa.Column('profile_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('diet_type', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=u'profile_ibfk_1'),
    sa.PrimaryKeyConstraint('profile_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('recipe',
    sa.Column('recipe_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recipe_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('recipe_picture', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('prep_time', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('calories', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('servings', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('diet_type', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('recipe_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('add_recipe',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], [u'recipe.recipe_id'], name=u'add_recipe_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=u'add_recipe_ibfk_1'),
    sa.PrimaryKeyConstraint('recipe_id', 'user_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('meal',
    sa.Column('meal_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('meal_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meal_type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('num_calorie', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('day', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('meal_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ingredients',
    sa.Column('ingredient_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ingredient_name', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('makes',
    sa.Column('meal_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], [u'meal.meal_id'], name=u'makes_ibfk_1', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], [u'recipe.recipe_id'], name=u'makes_ibfk_2', onupdate=u'CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'meal_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
